name: "first github action"

on: 
  push:
    branches:
      - 'main'
      - 'releases/**'
  workflow_dispatch: 

jobs:
- job: TerraformInit
  displayName: Init
  runs-on: gaurvrunner
  steps:
    - name: Print a greeting
      run: "echo" "Maharaj ki jai ho"
  
